---
exclude_paths:
  - ".agents/**"
  - ".codacy/**"
  - ".claude/**"
  - ".gemini/**"
  - ".github/**"
  - ".spec-workflow/**"
  - ".jules/**"
  - "deprecated/**"
  - "devops/**"
  - "docs/**"
  - "GEMINI.md"
  - "style.html"
  - "about/**"
  - "tests/**"
  - "vendor/**"
