---
exclude_paths:
  - ".agents/**"
  - ".codacy/**"
  - ".claude/**"
  - ".gemini/**"
  - ".github/**"
  - "deprecated/**"
  - "devops/**"
  - "docs/devops/**"
  - "GEMINI.md"
  - "style.html"
  - "about/**"
  - "docs/announcements.md"
  - "vendor/**"
